extends RefCounted

const SECTOR_SIZE := 1200.0
const HEIGHT_SCALE := 100.0
const WORLD_SCALE := 1.0 / SECTOR_SIZE
const EDGE_SLOPE := 150.0

const TERRAIN_AUTHORED_Y_OFFSET := 0.5

const BORDER_TYP_TOP_LEFT := 248
const BORDER_TYP_TOP := 252
const BORDER_TYP_TOP_RIGHT := 249
const BORDER_TYP_LEFT := 255
const BORDER_TYP_RIGHT := 253
const BORDER_TYP_BOTTOM_LEFT := 251
const BORDER_TYP_BOTTOM := 254
const BORDER_TYP_BOTTOM_RIGHT := 250

const SQUAD_FORMATION_SPACING := 100.0
const SQUAD_EXTRA_Y_OFFSET := 8.0
